# Generated by Django 5.2.3 on 2025-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
