# Generated by Django 5.2.3 on 2025-08-07 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_post_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
