# Generated by Django 5.2.3 on 2025-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
