# Generated by Django 5.2.3 on 2025-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="published",
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
