# Generated by Django 5.2.3 on 2025-08-23 15:12

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0006_remove_post_published_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
    ]
