# Generated by Django 5.2.3 on 2025-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
    ]
