# Generated by Django 5.2.3 on 2025-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="مقاله"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="عکس"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="مقاله ویژه"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان"),
        ),
    ]
