# Generated by Django 5.2.3 on 2025-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_alter_post_body_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="blogs/", verbose_name="عکس"),
        ),
    ]
