# Generated by Django 5.2.3 on 2025-09-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(related_name="posts", to="blogs.category"),
        ),
    ]
