# Generated by Django 5.2.3 on 2025-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_tag_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
