# Generated by Django 5.2.3 on 2025-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "Superuser"),
                    ("admin", "Admin"),
                    ("author", "Author"),
                    ("user", "User"),
                    ("premium", "Premium"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
