# Generated by Django 5.2.3 on 2025-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_image",
            field=models.ImageField(
                default="user_images/default-user-picture.png", upload_to="user_images"
            ),
        ),
    ]
